# 10. Matrix–Matrix Multiplication
From [D2L.ai Linear Algebra](https://d2l.ai/chapter_preliminaries/linear-algebra.html)

---


In [7]:
import torch

Initialize two matrices A and B:

In [8]:
A = torch.arange(6).reshape(2, 3)
B = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(A)
print(B)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


Matrix–matrix multiplication is performed by torch.mm():

In [9]:
C = torch.mm(A, B)
print(C)

tensor([[13, 16],
        [40, 52]])
