# 4. Tensors
From [D2L.ai Linear Algebra](https://d2l.ai/chapter_preliminaries/linear-algebra.html)

---


In [3]:
import torch

Tensors can be implemented as the following examples

- Scalar (0D tensor)

In [4]:
a = torch.tensor(3.14)
print(a)

tensor(3.1400)


- Vector (1D tensor)

In [5]:
b = torch.tensor([1.0, 2.0, 3.0])
print(b)

tensor([1., 2., 3.])


- Matrix (2D tensor)

In [6]:
c = torch.tensor([[1, 2], [3, 4]])
print(c)

tensor([[1, 2],
        [3, 4]])


- 3D Tensor: 2 matrices of shape (2x2)

In [7]:
d = torch.tensor([[[1, 2], [3, 4]],
[[5, 6], [7, 8]]])
print(d)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
