# 5. Basic Properties of Tensor Arithmetic
From [D2L.ai Linear Algebra](https://d2l.ai/chapter_preliminaries/linear-algebra.html)

---


In [1]:
import torch

In PyTorch, element-wise operations, broadcasting and Hadamard product can be implemented as the following examples:

Initialize three tensors A, B and C

In [2]:
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[10, 20], [30, 40]])
C = torch.tensor([10, 20])

- Element-wise addition


In [3]:
add = A + B
print(add)

tensor([[11, 22],
        [33, 44]])


- Element-wise multiplication

In [4]:
mul = A * B
print(mul)

tensor([[ 10,  40],
        [ 90, 160]])


- C is 1D but gets automatically expanded to match A’s shape

In [5]:
broadcast_result = A + C
print(broadcast_result)

tensor([[11, 22],
        [13, 24]])


- In PyTorch, Hadamard product is just element-wise multiplication

In [6]:

hadamard = A * B
print(hadamard)

tensor([[ 10,  40],
        [ 90, 160]])
