# 6. Reduction Operations
From [D2L.ai Linear Algebra](https://d2l.ai/chapter_preliminaries/linear-algebra.html)

---


In [5]:
import torch

Reduction operations decrease the number of elements in a tensor by aggregating values, such as calculating the sum, mean, or standard deviation.

In [6]:
# Assume we have the following rank-2 tensor of shape 3 x 3:
A = torch.tensor([
[0,1,0],
[2,0,2],
[0,3,0]
], dtype=torch.float32)

First, let's use the simplest reduction operation, sum():

In [7]:
print(A.sum())

tensor(8.)


The sum() method calculates the total of all elements, returning a tensor containing just a single scalar. We can confirm the reduction in tensor size:

In [8]:
print(A.numel())
print(A.sum().numel())
print(A.sum().numel() <= A.numel())

9
1
True


Other common reduction operations include:

In [9]:
print(A.sum()) # sum of elements
print(A.prod()) # product of elements
print(A.mean()) # mean (average) of elements
print(A.std()) # standard deviation of elements

tensor(8.)
tensor(0.)
tensor(0.8889)
tensor(1.1667)


Reduction operations don't always have to reduce tensors to a single scalar; they can also reduce tensors along specific axes:
- Axis 0 refers to reducing along columns (vertical direction).
- Axis 1 refers to reducing along rows (horizontal direction).
For instance, consider a rank-2 tensor with shape 3 x 4:

In [10]:
A = torch.tensor([
[1,1,1,1],
[2,2,2,2],
[3,3,3,3]
], dtype=torch.float32)

Performing a sum along each column (axis=0):

In [11]:
print(A.shape)
print(A.sum(axis=0))
print(A.sum(axis=0).shape)

torch.Size([3, 4])
tensor([6., 6., 6., 6.])
torch.Size([4])


Performing a sum along each row (axis=1):

In [12]:
print(A.sum(axis=1))
print(A.sum(axis=1).shape)

tensor([ 4.,  8., 12.])
torch.Size([3])


Reducing multiple axes simultaneously produces the same result as reducing the entire tensor directly:

In [13]:
print(A.sum(axis=[0,1]))
print(A.sum())

tensor(24.)
tensor(24.)


Similarly, computing the mean (average) of tensor elements is straightforward:

In [14]:
print(A.mean())
print(A.sum() / A.numel())

tensor(2.)
tensor(2.)


You can also calculate the mean along specific axes, for example:

In [15]:
print(A.mean(axis=0))
print(A.sum(axis=0) / A.shape[0])
print(A.mean(axis=1))
print(A.sum(axis=1) / A.shape[1])

tensor([2., 2., 2., 2.])
tensor([2., 2., 2., 2.])
tensor([1., 2., 3.])
tensor([1., 2., 3.])
