# 7. Non-reduction Operations
From [D2L.ai Linear Algebra](https://d2l.ai/chapter_preliminaries/linear-algebra.html)

---


In [1]:
import torch

Consider a tensor A defined as follows:

In [2]:
A = torch.tensor([[ 0, 1, 2, 3],
[ 4, 5, 6, 7],
[ 8, 9, 10, 11],
[12, 13, 14, 15],
[16, 17, 18, 19]], dtype=torch.float32)
print( A.shape)

torch.Size([5, 4])


This tensor has the shape (5,4), meaning it has 5 rows (axis 0) and 4 columns (axis 1). When summing along axis 1 without specifying keepdims, the resulting shape reduces to (5,), collapsing each row into a single scalar value:

In [3]:
print(A.sum(axis=1))
print(A.sum(axis=1).shape)

tensor([ 6., 22., 38., 54., 70.])
torch.Size([5])


If we set keepdims=True, the summed axis remains as a dimension of size 1, resulting in shape (5,1). Keeping this dimension can be particularly useful for subsequent calculations involving broadcasting, such as row-wise normalization:

In [4]:
sum_A = A.sum(axis=1, keepdims=True)
print(A / sum_A)

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])


Another useful function, cumsum(axis), calculates the cumulative sum along the specified axis without reducing dimensions. For example, applying cumulative sum vertically (along axis 0) results in a tensor of the same shape as the original:

In [5]:
print(A.cumsum(axis=0))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])
