# 9. Matrix–Vector Products
From [D2L.ai Linear Algebra](https://d2l.ai/chapter_preliminaries/linear-algebra.html)

---


In [7]:
import torch

Initialize a matrix A and a vector x:

In [8]:
A = torch.arange(6).reshape(2, 3)
x = torch.tensor([1, 2, 3])
print(A)
print(x)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([1, 2, 3])


the matrix–vector product can be computed using torch.mv():

In [9]:
y = torch.mv(A, x)
print(y)

tensor([ 8, 26])
