In [1]:
import numpy as np
if __name__ == "__main__":
    tensor = np.random.randint(0, 10, size=(2, 3, 4))
    print("Given tensor (shape {}):".format(tensor.shape))
    print(tensor)
    sum_axis0 = np.sum(tensor, axis=0)
    print("\nSummation along axis 0 (shape {}):".format(sum_axis0.shape))
    print(sum_axis0)
    sum_axis1 = np.sum(tensor, axis=1)
    print("\nSummation along axis 1 (shape {}):".format(sum_axis1.shape))
    print(sum_axis1)
    sum_axis2 = np.sum(tensor, axis=2)
    print("\nSummation along axis 2 (shape {}):".format(sum_axis2.shape))
    print(sum_axis2)


Given tensor (shape (2, 3, 4)):
[[[9 5 5 9]
  [7 7 3 1]
  [8 6 9 8]]

 [[8 6 0 2]
  [0 6 2 0]
  [4 7 8 3]]]

Summation along axis 0 (shape (3, 4)):
[[17 11  5 11]
 [ 7 13  5  1]
 [12 13 17 11]]

Summation along axis 1 (shape (2, 4)):
[[24 18 17 18]
 [12 19 10  5]]

Summation along axis 2 (shape (2, 3)):
[[28 18 31]
 [16  8 22]]
