In [1]:
import numpy as np
if __name__ == "__main__":
    X = np.random.randint(low=0, high=10, size=(2, 3, 4))
    print('X =', X)
    print('len(X) =', len(X))
    print('linalg.norm(X) =', np.linalg.norm(X))

X = [[[9 0 8 4]
  [0 0 3 4]
  [3 8 2 3]]

 [[9 2 6 8]
  [3 0 8 7]
  [4 5 8 7]]]
len(X) = 2
linalg.norm(X) = 27.073972741361768
